apiVersion: v2
name: simple-app
description: A minimal 3-tier Helm chart
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: postgresql
    version: "12.5.6"
    repository: "https://charts.bitnami.com/bitnami"
